# Generated by Django 5.2 on 2025-04-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflow_assigned_user_alter_workflow_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='workflows.customuser'),
        ),
    ]
