# Generated by Django 5.2 on 2025-04-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflow_status_alter_workflow_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.customuser'),
        ),
    ]
